<?php

//////////////////////////////////////////////////////////////////////////////
// $Id: xoops_version.php,v 1.5 23/11/2005 13:40:31 BitC3R0 Exp $           //
// ------------------------------------------------------------------------ //
// RM+Soft Downloads Plus 1.5                                               //
// Copyright © 2005. Red Mexico Soft                                        //
// <www.redmexico.com.mx>                                                   //
// Modulo XOOPS que permite el control y distribución avanzado de           //
// descargas.                                                               //
// ------------------------------------------------------------------------ //
// This program is free software; you can redistribute it and/or modify     //
// it under the terms of the GNU General Public License as published by     //
// the Free Software Foundation; either version 2 of the License, or        //
// (at your option) any later version.                                      //
//                                                                          //
// This program is distributed in the hope that it will be useful, but      //
// WITHOUT ANY WARRANTY; without even the implied warranty of               //
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU         //
// General Public License for more details.                                 //
//                                                                          //
// You should have received a copy of the GNU General Public License        //
// along with this program; if not, write to the                            //
// Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,      //
// MA 02111-1307 USA                                                        //
// ------------------------------------------------------------------------ //
// Questions, Bugs or any comment plese write me                            //
// Preguntas, errores o cualquier comentario escribeme                      //
// <adminone@redmexico.com.mx>                                              //
// ------------------------------------------------------------------------ //
// Visita http://www.xoops-mexico.net para obtener los últimos módulos      //
// de Red México Soft.                                                      //
//                                                                          //
// For more modules from Red México Soft visit http://www.xoops-mexico.net  //
// ------------------------------------------------------------------------ //
//////////////////////////////////////////////////////////////////////////////

$modversion['name'] = _MI_RMDP_NAME;
$modversion['version'] = 1.5;
$modversion['description'] = _MI_RMDP_DESC;
$modversion['author'] = '(AdminOne) http://www.redmexico.com.mx';
$modversion['credits'] = 'AdminOne - RM+Soft';
$modversion['help'] = 'http://www.xoops-mexico.net/modules/rmlib/books.php?book=5';
$modversion['license'] = 'GPL see LICENSE';
$modversion['official'] = 0;
$modversion['image'] = 'images/logo.png';
$modversion['dirname'] = 'rmdp';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/rmdp.sql';
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'rmdp_categos';
$modversion['tables'][1] = 'rmdp_plataformas';
$modversion['tables'][2] = 'rmdp_softos';
$modversion['tables'][3] = 'rmdp_software';
$modversion['tables'][4] = 'rmdp_shots';
$modversion['tables'][5] = 'rmdp_partners';
$modversion['tables'][6] = 'rmdp_licences';
$modversion['tables'][7] = 'rmdp_sended';
$modversion['tables'][8] = 'rmdp_data';
$modversion['tables'][9] = 'rmdp_editorcom';
$modversion['tables'][10] = 'rmdp_votes';
$modversion['tables'][11] = 'rmdp_mirrors';

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu'] = 'admin/menu.php';

$modversion['hasMain'] = 1;
$modversion['sub'][1]['name'] = _MI_SEND_DOWNLOAD;
$modversion['sub'][1]['url'] = 'submit.php';
$modversion['sub'][2]['name'] = _MI_SENDED_DOWNS;
$modversion['sub'][2]['url'] = 'mysends.php';

// Blocks
// Descargas recientes
$modversion['blocks'][1]['file'] = 'rmdp_recent_downs.php';
$modversion['blocks'][1]['name'] = _MI_RMDP_RECENT_TITLE;
$modversion['blocks'][1]['description'] = 'Muestra las descargas recientes';
$modversion['blocks'][1]['show_func'] = 'rmdp_b_show_recent';
$modversion['blocks'][1]['edit_func'] = 'rmdp_b_show_recent_edit';
$modversion['blocks'][1]['options'] = '5';
$modversion['blocks'][1]['template'] = 'rmdp_recent.html';

//Descargas Populares
$modversion['blocks'][2]['file'] = 'rmdp_popular_downs.php';
$modversion['blocks'][2]['name'] = _MI_RMDP_POPULARTITLE;
$modversion['blocks'][2]['description'] = 'Muestra las descargas populares';
$modversion['blocks'][2]['show_func'] = 'rmdp_b_show_populars';
$modversion['blocks'][2]['edit_func'] = 'rmdp_b_show_populars_edit';
$modversion['blocks'][2]['options'] = '10|50|20';
$modversion['blocks'][2]['template'] = 'rmdp_populars.html';

// Descargas actualizadas
$modversion['blocks'][3]['file'] = 'rmdp_update_downs.php';
$modversion['blocks'][3]['name'] = _MI_RMDP_UPDATETITLE;
$modversion['blocks'][3]['description'] = 'Muestra las descargas actualizadas';
$modversion['blocks'][3]['show_func'] = 'rmdp_b_show_updated';
$modversion['blocks'][3]['edit_func'] = 'rmdp_b_show_update_edit';
$modversion['blocks'][3]['options'] = '10|20';
$modversion['blocks'][3]['template'] = 'rmdp_update.html';

// Descargas mejor valoradas
$modversion['blocks'][4]['file'] = 'rmdp_best_rated.php';
$modversion['blocks'][4]['name'] = _MI_RMDP_RATEDTITLE;
$modversion['blocks'][4]['description'] = 'Muestra las descargas mejor valoradas';
$modversion['blocks'][4]['show_func'] = 'rmdp_b_show_rated';
$modversion['blocks'][4]['edit_func'] = 'rmdp_b_show_rated_edit';
$modversion['blocks'][4]['options'] = '10|20';
$modversion['blocks'][4]['template'] = 'rmdp_bestrated.html';

// Última descarga creada
$modversion['blocks'][5]['file'] = 'rmdp_lastdown.php';
$modversion['blocks'][5]['name'] = _MI_RMDP_LASTDOWN;
$modversion['blocks'][5]['description'] = 'Muestra la última descarga agregada';
$modversion['blocks'][5]['show_func'] = 'rmdp_b_show_lastdown';
$modversion['blocks'][5]['edit_func'] = 'rmdp_b_edit_lastdown';
$modversion['blocks'][5]['options'] = '1|1|d/m/Y';
$modversion['blocks'][5]['template'] = 'rmdp_lastdown.html';

// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = 'include/rmdp_xoops_search.php';
$modversion['search']['func'] = 'rmdp_xoops_search';

// Templates
$modversion['templates'][1]['file'] = 'rmdp_index.html';
$modversion['templates'][1]['description'] = '';
$modversion['templates'][2]['file'] = 'rmdp_categos.html';
$modversion['templates'][2]['description'] = '';
$modversion['templates'][4]['file'] = 'rmdp_download_now.html';
$modversion['templates'][4]['description'] = '';
$modversion['templates'][5]['file'] = 'rmdp_download_data.html';
$modversion['templates'][5]['description'] = '';
$modversion['templates'][6]['file'] = 'rmdp_shots.html';
$modversion['templates'][6]['description'] = '';
$modversion['templates'][7]['file'] = 'rmdp_shots_view.html';
$modversion['templates'][7]['description'] = '';
$modversion['templates'][8]['file'] = 'rmdp_view_popular.html';
$modversion['templates'][8]['description'] = '';
$modversion['templates'][9]['file'] = 'rmdp_submit.html';
$modversion['templates'][9]['description'] = '';
$modversion['templates'][10]['file'] = 'rmdp_show_sends.html';
$modversion['templates'][10]['description'] = '';
$modversion['templates'][11]['file'] = 'rmdp_search_result.html';
$modversion['templates'][11]['description'] = '';
$modversion['templates'][12]['file'] = 'rmdp_modify_submit.html';
$modversion['templates'][12]['description'] = '';
$modversion['templates'][13]['file'] = 'rmdp_send_shots.html';
$modversion['templates'][13]['description'] = '';
$modversion['templates'][14]['file'] = 'rmdp_categos_simple.html';
$modversion['templates'][14]['description'] = '';
$modversion['templates'][15]['file'] = 'rmdp_categos_images.html';
$modversion['templates'][15]['description'] = '';
$modversion['templates'][16]['file'] = 'rmdp_downloads_rss.xml';
$modversion['templates'][16]['description'] = '';

// Categorpias de Configuración
$modversion['configcat'][1]['nameid'] = 'downloads';
$modversion['configcat'][1]['name'] = '_MI_RMDP_CONFIGCAT_DOWNS';
$modversion['configcat'][1]['description'] = '';

$modversion['configcat'][2]['nameid'] = 'images';
$modversion['configcat'][2]['name'] = '_MI_RMDP_CONFIGCAT_IMGS';
$modversion['configcat'][2]['description'] = '';

// Opcion para configurar el titulo del modulo
$modversion['config'][1]['name'] = 'rmdptitle';
$modversion['config'][1]['title'] = '_MI_RMDP_MODTITLE';
$modversion['config'][1]['description'] = '';
$modversion['config'][1]['formtype'] = 'textbox';
$modversion['config'][1]['valuetype'] = 'text';
$modversion['config'][1]['default'] = 'Descargas';

// Tamaño (width) para las imágenes de las categorías
$modversion['config'][2]['name'] = 'imgcategow';
$modversion['config'][2]['title'] = '_MI_RMDP_CATGOIMGW';
$modversion['config'][2]['description'] = '';
$modversion['config'][2]['formtype'] = 'textbox';
$modversion['config'][2]['valuetype'] = 'int';
$modversion['config'][2]['default'] = '80';
$modversion['config'][2]['category'] = 'images';

// Tamaño (width) para las imágenes de las categorías
$modversion['config'][3]['name'] = 'showimgcat';
$modversion['config'][3]['title'] = '_MI_RMDP_SHOWCATIMG';
$modversion['config'][3]['description'] = '';
$modversion['config'][3]['formtype'] = 'yesno';
$modversion['config'][3]['valuetype'] = 'int';
$modversion['config'][3]['default'] = 0;
$modversion['config'][3]['category'] = 'images';

// Tamaño (width) para las imágenes de descargas
$modversion['config'][4]['name'] = 'imgdownw';
$modversion['config'][4]['title'] = '_MI_RMDP_DOWNIMGW';
$modversion['config'][4]['description'] = '';
$modversion['config'][4]['formtype'] = 'textbox';
$modversion['config'][4]['valuetype'] = 'int';
$modversion['config'][4]['default'] = '80';
$modversion['config'][4]['category'] = 'images';

// Tamaño (width) para las imágenes pequeñas de pantallas
$modversion['config'][5]['name'] = 'imgshotsw';
$modversion['config'][5]['title'] = '_MI_RMDP_SHOTIMGW';
$modversion['config'][5]['description'] = '';
$modversion['config'][5]['formtype'] = 'textbox';
$modversion['config'][5]['valuetype'] = 'int';
$modversion['config'][5]['default'] = '80';
$modversion['config'][5]['category'] = 'images';

// Tamaño (width) para las imágenes grandes de pantallas
$modversion['config'][6]['name'] = 'imgshotbw';
$modversion['config'][6]['title'] = '_MI_RMDP_SHOTIMGBIGW';
$modversion['config'][6]['description'] = _MI_RMDP_SHOTIMGBIGD;
$modversion['config'][6]['formtype'] = 'textbox';
$modversion['config'][6]['valuetype'] = 'int';
$modversion['config'][6]['default'] = '400';
$modversion['config'][6]['category'] = 'images';

// Comportamiento de los vinculos de pantallas
$modversion['config'][7]['name'] = 'shotlink';
$modversion['config'][7]['title'] = '_MI_RMDP_SHOTLINK';
$modversion['config'][7]['description'] = '_MI_RMDP_SHOTLINK_DESC';
$modversion['config'][7]['formtype'] = 'yesno';
$modversion['config'][7]['valuetype'] = 'int';
$modversion['config'][7]['default'] = '0';
$modversion['config'][7]['category'] = 'images';

// Limite de pantallas por descarga
$modversion['config'][8]['name'] = 'shotlimit';
$modversion['config'][8]['title'] = '_MI_RMDP_SHOTLIMIT';
$modversion['config'][8]['description'] = '';
$modversion['config'][8]['formtype'] = 'textbox';
$modversion['config'][8]['valuetype'] = 'int';
$modversion['config'][8]['default'] = 5;
$modversion['config'][8]['category'] = 'images';

// Dias para considerar una categoria como nueva
$modversion['config'][9]['name'] = 'categonew';
$modversion['config'][9]['title'] = '_MI_RMDP_CATEGODAYSNEW';
$modversion['config'][9]['description'] = '';
$modversion['config'][9]['formtype'] = 'select';
$modversion['config'][9]['valuetype'] = 'int';
$modversion['config'][9]['default'] = 10;
$modversion['config'][9]['options'] = ['5 días' => 5, '10 días' => 10, '20 días' => 20, '30 días' => 30];

// Número de subcategorías para mostrar en cada categoría
$modversion['config'][10]['name'] = 'subcategoslimit';
$modversion['config'][10]['title'] = '_MI_RMDP_SUBCATLIMIT';
$modversion['config'][10]['description'] = '';
$modversion['config'][10]['formtype'] = 'textbox';
$modversion['config'][10]['valuetype'] = 'int';
$modversion['config'][10]['default'] = 5;

// Dias para considerar una característica como nueva
$modversion['config'][11]['name'] = 'caractnew';
$modversion['config'][11]['title'] = '_MI_RMDP_CARACTDAYSNEW';
$modversion['config'][11]['description'] = '';
$modversion['config'][11]['formtype'] = 'select';
$modversion['config'][11]['valuetype'] = 'int';
$modversion['config'][11]['default'] = 10;
$modversion['config'][11]['options'] = ['5 días' => 5, '10 días' => 10, '20 días' => 20, '30 días' => 30];

// Dias para considerar una pantalla como nueva
$modversion['config'][12]['name'] = 'shotnew';
$modversion['config'][12]['title'] = '_MI_RMDP_SHOTDAYSNEW';
$modversion['config'][12]['description'] = '';
$modversion['config'][12]['formtype'] = 'select';
$modversion['config'][12]['valuetype'] = 'int';
$modversion['config'][12]['default'] = 5;
$modversion['config'][12]['options'] = ['5 días' => 5, '10 días' => 10, '20 días' => 20, '30 días' => 30];
$modversion['config'][12]['category'] = 'images';

// Activar el envió de descargas
$modversion['config'][13]['name'] = 'downsend';
$modversion['config'][13]['title'] = '_MI_RMDP_SENDDOWN';
$modversion['config'][13]['description'] = '';
$modversion['config'][13]['formtype'] = 'yesno';
$modversion['config'][13]['valuetype'] = 'int';
$modversion['config'][13]['default'] = 1;
$modversion['config'][13]['category'] = 'downloads';

// Permitir el envío de Archivos
$modversion['config'][14]['name'] = 'filesend';
$modversion['config'][14]['title'] = '_MI_RMDP_SENDFILES';
$modversion['config'][14]['description'] = _MI_RMDP_SENDFILE_DESC;
$modversion['config'][14]['formtype'] = 'yesno';
$modversion['config'][14]['valuetype'] = 'int';
$modversion['config'][14]['default'] = 1;
$modversion['config'][14]['category'] = 'downloads';

// Permitir el envío de Imágenes
$modversion['config'][15]['name'] = 'imagesend';
$modversion['config'][15]['title'] = '_MI_RMDP_SENDIMG';
$modversion['config'][15]['description'] = '_MI_RMDP_SENDIMG_DESC';
$modversion['config'][15]['formtype'] = 'yesno';
$modversion['config'][15]['valuetype'] = 'int';
$modversion['config'][15]['default'] = 1;
$modversion['config'][15]['category'] = 'images';

// Permitir a los usuarios anónimos enviar descargas
$modversion['config'][16]['name'] = 'sendanonimo';
$modversion['config'][16]['title'] = '_MI_RMDP_SENDANONIMO';
$modversion['config'][16]['description'] = '';
$modversion['config'][16]['formtype'] = 'yesno';
$modversion['config'][16]['valuetype'] = 'int';
$modversion['config'][16]['default'] = 0;
$modversion['config'][16]['category'] = 'downloads';

// Numero de descargas patrocinadas en la página principal
$modversion['config'][17]['name'] = 'sponsor_downs';
$modversion['config'][17]['title'] = '_MI_RMDP_SPONSORNUM';
$modversion['config'][17]['description'] = '';
$modversion['config'][17]['formtype'] = 'textbox';
$modversion['config'][17]['valuetype'] = 'int';
$modversion['config'][17]['default'] = 3;
$modversion['config'][17]['category'] = 'downloads';

// Numero de descargas a mostrar en "Favoritos"
$modversion['config'][18]['name'] = 'favo_downs';
$modversion['config'][18]['title'] = '_MI_RMDP_FAVORITESNUM';
$modversion['config'][18]['description'] = '';
$modversion['config'][18]['formtype'] = 'select';
$modversion['config'][18]['valuetype'] = 'int';
$modversion['config'][18]['default'] = 5;
$modversion['config'][18]['options'] = ['5' => 5, '10' => 10, '15' => 15, '20' => 20];
$modversion['config'][18]['category'] = 'downloads';

// Numero de descargas a mostrar en "Populares"
$modversion['config'][19]['name'] = 'popular_downs';
$modversion['config'][19]['title'] = '_MI_RMDP_POPULARNUM';
$modversion['config'][19]['description'] = '';
$modversion['config'][19]['formtype'] = 'select';
$modversion['config'][19]['valuetype'] = 'int';
$modversion['config'][19]['default'] = 5;
$modversion['config'][19]['options'] = ['5' => 5, '10' => 10, '15' => 15, '20' => 20];
$modversion['config'][19]['category'] = 'downloads';

// Numero de carácteres a mostrar en descripción de descargas patrocinadas
$modversion['config'][20]['name'] = 'len_desc';
$modversion['config'][20]['title'] = '_MI_RMDP_LENDESC';
$modversion['config'][20]['description'] = '';
$modversion['config'][20]['formtype'] = 'textbox';
$modversion['config'][20]['valuetype'] = 'int';
$modversion['config'][20]['default'] = 100;
$modversion['config'][20]['category'] = 'downloads';

// Color de Fondo para descargas resaltadas
$modversion['config'][21]['name'] = 'bgresalte';
$modversion['config'][21]['title'] = '_MI_RMDP_RESALTEBG';
$modversion['config'][21]['description'] = '';
$modversion['config'][21]['formtype'] = 'textbox';
$modversion['config'][21]['valuetype'] = 'text';
$modversion['config'][21]['default'] = '#EBEBEB';
$modversion['config'][21]['category'] = 'downloads';

// Numero de Resultados por página
$modversion['config'][22]['name'] = 'limit_result';
$modversion['config'][22]['title'] = '_MI_RMDP_LIMITRESULT';
$modversion['config'][22]['description'] = '';
$modversion['config'][22]['formtype'] = 'textbox';
$modversion['config'][22]['valuetype'] = 'int';
$modversion['config'][22]['default'] = 10;

// Dias para considerar un elemento como actualizado
$modversion['config'][23]['name'] = 'update_days';
$modversion['config'][23]['title'] = '_MI_RMDP_UPDATEDAYS';
$modversion['config'][23]['description'] = '';
$modversion['config'][23]['formtype'] = 'select';
$modversion['config'][23]['valuetype'] = 'int';
$modversion['config'][23]['default'] = 10;
$modversion['config'][23]['options'] = ['5 días' => 5, '10 días' => 10, '15 días' => 15, '20 días' => 20, '30 días' => 30];

// Dias para considerar una descarga como nueva
$modversion['config'][24]['name'] = 'downnew';
$modversion['config'][24]['title'] = '_MI_RMDP_DOWNNEW';
$modversion['config'][24]['description'] = '';
$modversion['config'][24]['formtype'] = 'select';
$modversion['config'][24]['valuetype'] = 'int';
$modversion['config'][24]['default'] = 10;
$modversion['config'][24]['options'] = ['5 días' => 5, '10 días' => 10, '15 días' => 15, '20 días' => 20, '30 días' => 30];
$modversion['config'][24]['category'] = 'downloads';

// Formato de fecha
$modversion['config'][25]['name'] = 'dateformat';
$modversion['config'][25]['title'] = '_MI_RMDP_DATEFORMAT';
$modversion['config'][25]['description'] = '';
$modversion['config'][25]['formtype'] = 'textbox';
$modversion['config'][25]['valuetype'] = 'text';
$modversion['config'][25]['default'] = 'd/m/Y';

// Numero de descargas para considerar un elemento como popular
$modversion['config'][26]['name'] = 'popular_needs';
$modversion['config'][26]['title'] = '_MI_RMDP_POPULARNEEDS';
$modversion['config'][26]['description'] = '';
$modversion['config'][26]['formtype'] = 'textbox';
$modversion['config'][26]['valuetype'] = 'int';
$modversion['config'][26]['default'] = 100;
$modversion['config'][26]['category'] = 'downloads';

// Permitir a los usuarios anonimos votar
$modversion['config'][27]['name'] = 'uservote';
$modversion['config'][27]['title'] = '_MI_RMDP_USERVOTE';
$modversion['config'][27]['description'] = '';
$modversion['config'][27]['formtype'] = 'yesno';
$modversion['config'][27]['valuetype'] = 'int';
$modversion['config'][27]['default'] = 0;

// Abrir descargas en nueva ventana
$modversion['config'][28]['name'] = 'newwindow';
$modversion['config'][28]['title'] = '_MI_RMDP_OPENWINDOW';
$modversion['config'][28]['description'] = '';
$modversion['config'][28]['formtype'] = 'select';
$modversion['config'][28]['valuetype'] = 'int';
$modversion['config'][28]['default'] = 0;
$modversion['config'][28]['options'] = [_MI_RMDP_OPENSAME => 0, _MI_RMDP_OPENNEW => 1];

// Columnas para las pantallas de descargas
$modversion['config'][29]['name'] = 'shotcols';
$modversion['config'][29]['title'] = '_MI_RMDP_SHOTCOLS';
$modversion['config'][29]['description'] = '';
$modversion['config'][29]['formtype'] = 'select';
$modversion['config'][29]['valuetype'] = 'int';
$modversion['config'][29]['default'] = 3;
$modversion['config'][29]['options'] = ['1' => 1, '2' => 2, '3' => 3, '4' => 4, '5' => 5];
$modversion['config'][29]['category'] = 'images';

// Número de descargas populares a mostrar
$modversion['config'][30]['name'] = 'toppop';
$modversion['config'][30]['title'] = '_MI_RMDP_TOPPOP';
$modversion['config'][30]['description'] = '';
$modversion['config'][30]['formtype'] = 'textbox';
$modversion['config'][30]['valuetype'] = 'int';
$modversion['config'][30]['default'] = 15;
$modversion['config'][30]['category'] = 'downloads';

// Número de descargas mejor votadas a mostrar
$modversion['config'][31]['name'] = 'toprate';
$modversion['config'][31]['title'] = '_MI_RMDP_TOPRATE';
$modversion['config'][31]['description'] = '';
$modversion['config'][31]['formtype'] = 'textbox';
$modversion['config'][31]['valuetype'] = 'int';
$modversion['config'][31]['default'] = 20;
$modversion['config'][31]['category'] = 'downloads';

// Enviar notificación por email cuando se recibe una descarga
$modversion['config'][32]['name'] = 'senmail';
$modversion['config'][32]['title'] = '_MI_RMDP_SENDMAIL';
$modversion['config'][32]['description'] = '';
$modversion['config'][32]['formtype'] = 'yesno';
$modversion['config'][32]['valuetype'] = 'int';
$modversion['config'][32]['default'] = 1;

// cuerpo del email de configmración para usuarios
$modversion['config'][33]['name'] = 'bodymail';
$modversion['config'][33]['title'] = '_MI_RMDP_BODYMAIL';
$modversion['config'][33]['description'] = '_MI_RMDP_BODYMAIL_DESC';
$modversion['config'][33]['formtype'] = 'textarea';
$modversion['config'][33]['valuetype'] = 'text';

// Texto informativo para usuarios que desean reportar un enlace roto
$modversion['config'][34]['name'] = 'brokentext';
$modversion['config'][34]['title'] = '_MI_RMDP_BORKENINFO';
$modversion['config'][34]['description'] = '';
$modversion['config'][34]['formtype'] = 'textarea';
$modversion['config'][34]['valuetype'] = 'text';

// Directorio para almacenar archivos enviados
$modversion['config'][35]['name'] = 'softdir';
$modversion['config'][35]['title'] = '_MI_RMDP_SOFTDIR';
$modversion['config'][35]['description'] = '_MI_RMDP_SOFTDIR_DESC';
$modversion['config'][35]['formtype'] = 'textbox';
$modversion['config'][35]['valuetype'] = 'text';
$modversion['config'][35]['default'] = 'XOOPS_ROOT_PATH/modules/rmdp/uploads';

// Mirrors de descargas
$modversion['config'][36]['name'] = 'mirrors';
$modversion['config'][36]['title'] = '_MI_RMDP_MIRRORSNUM';
$modversion['config'][36]['description'] = '_MI_RMDP_MIRRORSNUM_DESC';
$modversion['config'][36]['formtype'] = 'select';
$modversion['config'][36]['valuetype'] = 'int';
$modversion['config'][36]['default'] = '3';
$modversion['config'][36]['options'] = ['0' => 0, '1' => 1, '2' => 2, '3' => 3, '4' => 4, '5' => 5, '10' => 10];

// Tamaño del archivo a subir
$modversion['config'][37]['name'] = 'filesize';
$modversion['config'][37]['title'] = '_MI_RMDP_FILESIZE';
$modversion['config'][37]['description'] = '';
$modversion['config'][37]['formtype'] = 'textbox';
$modversion['config'][37]['valuetype'] = 'int';
$modversion['config'][37]['default'] = '1';

// MUnidad de conversión del tamaño
$modversion['config'][38]['name'] = 'sizeunit';
$modversion['config'][38]['title'] = '_MI_RMDP_SIZEUNIT';
$modversion['config'][38]['description'] = '';
$modversion['config'][38]['formtype'] = 'select';
$modversion['config'][38]['valuetype'] = 'int';
$modversion['config'][38]['default'] = 1024;
$modversion['config'][38]['options'] = ['BYTES' => 1, 'KB' => 1024, 'MB' => 1048576];

// Tipo de Editor
$modversion['config'][39]['name'] = 'editor';
$modversion['config'][39]['title'] = '_AM_RMDP_EDITOR';
$modversion['config'][39]['description'] = '';
$modversion['config'][39]['formtype'] = 'select';
$modversion['config'][39]['valuetype'] = 'text';
$modversion['config'][39]['default'] = 'dhtml';
$modversion['config'][39]['options'] = [
    _MI_RMDP_FORM_DHTML => 'dhtml',
_MI_RMDP_FORM_COMPACT => 'textarea',
_MI_RMDP_FORM_SPAW => 'spaw',
_MI_RMDP_FORM_HTMLAREA => 'htmlarea',
_MI_RMDP_FORM_KOIVI => 'koivi',
_MI_RMDP_FORM_FCK => 'fck',
];

// Tamaño del archivo a subir
$modversion['config'][40]['name'] = 'types';
$modversion['config'][40]['title'] = '_MI_RMDP_FILETYPES';
$modversion['config'][40]['description'] = '_MI_RMDP_FILETYPES_DESC';
$modversion['config'][40]['formtype'] = 'textbox';
$modversion['config'][40]['valuetype'] = 'text';
$modversion['config'][40]['default'] = '.zip|.tar|.gz|.rar|.jpg|.png|.pdf|.bz2';
$modversion['config'][40]['category'] = 'downloads';

// Activar Banners
$modversion['config'][41]['name'] = 'banners';
$modversion['config'][41]['title'] = '_MI_RMDP_BANNERS';
$modversion['config'][41]['description'] = '';
$modversion['config'][41]['formtype'] = 'yesno';
$modversion['config'][41]['valuetype'] = 'int';
$modversion['config'][41]['default'] = 0;

// Código para mostrar banners
$modversion['config'][42]['name'] = 'banncode';
$modversion['config'][42]['title'] = '_MI_RMDP_BANNERS_CODE';
$modversion['config'][42]['description'] = '';
$modversion['config'][42]['formtype'] = 'textarea';
$modversion['config'][42]['valuetype'] = 'text';
$modversion['config'][42]['default'] = '';

// Tiempo de retardo para iniciar una descarga
$modversion['config'][43]['name'] = 'retardo';
$modversion['config'][43]['title'] = '_MI_RMDP_RETARDO';
$modversion['config'][43]['description'] = '_MI_RMDP_RETARDO_DESC';
$modversion['config'][43]['formtype'] = 'select';
$modversion['config'][43]['valuetype'] = 'int';
$modversion['config'][43]['default'] = '5';
$modversion['config'][43]['options'] = ['1' => 1, '2' => 2, '3' => 3, '4' => 4, '5' => 5, '6' => 6, '7' => 7, '8' => 8, '9' => 9, '10' => 10];
$modversion['config'][43]['category'] = 'downloads';

// Comentarios
$modversion['hasComments'] = 1;
$modversion['comments']['itemName'] = 'id';
$modversion['comments']['pageName'] = 'down.php';
$modversion['comments']['extraParams'] = ['cid'];

// Comment callback functions
$modversion['comments']['callbackFile'] = 'include/rmdp_comments.php';
$modversion['comments']['callback']['approve'] = 'rmdp_com_approve';
$modversion['comments']['callback']['update'] = 'rmdp_com_update';



